config/routes.rb
Rails.application.routes.draw do
  resources :categories, :soups

  root to: "categories#index"

  get "/allcategories", to: redirect("/")

  get "/soups/:id/toggle_featured", to: "soups#toggle_featured", as: :toggle_featured

  get "/secret_soups", to: "categories#secret_soups"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :soups
end

app/models/soup.rb
class Soup < ActiveRecord::Base
	belongs_to :category

	validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
	end

	def show
		@category = Category.find(params[:id])
	end

	def secret_soups
		session[:vip] = true
		redirect_to root_path
	end
end

app/controllers/soups_controller.rb
class SoupsController < ApplicationController
	before_action :fetch_soup, only: [:show, :new, :edit, :update, :destroy, :toggle_featured] 

	def show
		respond_to do |format|
			format.html
			format.json { render json: @soup }
		end
	end

	def index
		@soups = Soup.all

		respond_to do |format|
			format.json { render json: @soups}
		end
	end

	def new
		
	end

	def edit
		
	end

	def update
		
	end

	def destroy
		
	end

	def toggle_featured
		@soup.toggle!(:featured)
		flash[:notice] = "Successfully changed the featured flag."
		redirect_to @soup
	end

	private

	def fetch_soup
		@soup = Soup.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/soups_helper.rb
module SoupsHelper
end

app/views/categories/index.html.erb
<h1>Soup Categories</h1>
<ul>
<% @categories.each do |category| %>
	<li><%= link_to category.name, category %> (<%= category.soups.size %>)</li>
	<% end %>
	<% if session[:vip] %>
		<li>Super Secret Bouillon</li>
	<%end%>
</ul>

app/views/categories/show.html.erb
<h1>Category: <%= @category.name%></h1>
<ul>
	<% @category.soups.each do |soup|%>
	<li>
		Soup: <%= link_to soup.name, soup %>
	</li>
	<% end %>
</ul>

<p><%= link_to "Back to Soup Categories", categories_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoupToBits</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
	<p><%= flash[:notice] %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/soups/show.html.erb
<h1><%= @soup.name %></h1>

<% if @soup.featured? %>
	<p>This delicious soup is featured this month.</p>
	<% else %>
	<p>This soup is not is season, so it kinda sucks right now...</p>
	<% end %>
<% if params[:admin] == "true" %>
	<p><%= link_to "Toggle Featured", toggle_featured_path(@soup)%></p>
<% end %>